StockScreener/Models/ErrorViewModel.cs
using System;

namespace StockScreener.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StockScreener/Models/StockPurchase.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace StockScreener.Models
{
    public class StockPurchase
    {
        public int Id { get; set; }
        public double BoughtAt { get; set; }
        public string StockIndex { get; set; }
        public double SharesQuantity { get; set; }
        public string UserName { get; set; }
        public double WinLoss { get; set; }
    }
}

StockScreener/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using RestSharp;
using StockScreener.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using YahooFinanceApi;

namespace StockScreener.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StockScreener/Controllers/Stock/StockPurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StockScreener.Data;
using StockScreener.Models;
using YahooFinanceApi;

namespace StockScreener.Controllers.Stock
{
    public class StockPurchasesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StockPurchasesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult NotLoggedIn()
        {
            return View();
        }

        public IActionResult IndexError()
        {
            return View();
        }
        public IActionResult InputError()
        {
            return View();
        }

        // GET: StockPurchases
        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated) { return RedirectToAction("NotLoggedIn"); }
            string userName = HttpContext.User.Identity.Name;
            foreach (var cos in _context.StockPurchase.Where(s => s.UserName == userName))
            {
                var securities = await Yahoo.Symbols(cos.StockIndex).Fields(Field.Symbol, Field.RegularMarketPrice, Field.FiftyTwoWeekHigh).QueryAsync();
                var stock = securities[cos.StockIndex];
                var price = Math.Round((stock[Field.RegularMarketPrice] * cos.SharesQuantity) - (cos.SharesQuantity * cos.BoughtAt),2);
                cos.WinLoss = price;
            }
          
            return View(await _context.StockPurchase.Where(s => s.UserName == userName)
                                      .ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (!User.Identity.IsAuthenticated) { return RedirectToAction("NotLoggedIn"); }
            if (id == null)
            {
                return NotFound();
            }

            var stockPurchase = await _context.StockPurchase
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stockPurchase == null)
            {
                return NotFound();
            }

            return View(stockPurchase);
        }

        public IActionResult Create()
        {
            if (!User.Identity.IsAuthenticated) { return RedirectToAction("NotLoggedIn"); }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BoughtAt,StockIndex,SharesQuantity,UserName")] StockPurchase stockPurchase)
        {
            string userName = HttpContext.User.Identity.Name;
            try
            {
                var securities = await Yahoo.Symbols(stockPurchase.StockIndex).Fields(Field.Symbol, Field.RegularMarketPrice, Field.FiftyTwoWeekHigh).QueryAsync();
                stockPurchase.UserName = userName;
                stockPurchase.WinLoss = 0;
                if (!TryValidateModel(stockPurchase)) { return RedirectToAction("InputError"); }

                if (securities.ContainsKey(stockPurchase.StockIndex))
                    {          
                        _context.Add(stockPurchase);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));                  
                    }
            }
            catch(Exception e)
            {
                return RedirectToAction("IndexError");
            }
            
            return View(stockPurchase);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (!User.Identity.IsAuthenticated) { return RedirectToAction("NotLoggedIn"); }
            if (id == null)
            {
                return NotFound();
            }

            var stockPurchase = await _context.StockPurchase.FindAsync(id);
            if (stockPurchase == null)
            {
                return NotFound();
            }
            return View(stockPurchase);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BoughtAt,StockIndex,SharesQuantity,UserName")] StockPurchase stockPurchase)
        {
            var securities = await Yahoo.Symbols(stockPurchase.StockIndex).Fields(Field.Symbol, Field.RegularMarketPrice, Field.FiftyTwoWeekHigh).QueryAsync();
            string userName = HttpContext.User.Identity.Name;
            if (id != stockPurchase.Id)
            {
                return NotFound();
            }

            if (!TryValidateModel(stockPurchase)) { return RedirectToAction("InputError"); }
            if (securities.ContainsKey(stockPurchase.StockIndex))
            {
                try
                {
                    stockPurchase.UserName = userName;
                    _context.Update(stockPurchase);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockPurchaseExists(stockPurchase.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stockPurchase);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (!User.Identity.IsAuthenticated) { return RedirectToAction("NotLoggedIn"); }
            if (id == null)
            {
                return NotFound();
            }

            var stockPurchase = await _context.StockPurchase
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stockPurchase == null)
            {
                return NotFound();
            }

            return View(stockPurchase);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stockPurchase = await _context.StockPurchase.FindAsync(id);
            _context.StockPurchase.Remove(stockPurchase);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StockPurchaseExists(int id)
        {
            return _context.StockPurchase.Any(e => e.Id == id);
        }
    }
}

StockScreener/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="container px-4 py-5" id="featured-3">
    <h2 class="pb-2 border-bottom">What do you want to do?</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="feature col">
            <div class="feature-icon bg-dark bg-gradient rounded position-relative top-0 start-50 translate-middle-x" style="width:80px">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="white" class="bi bi-collection m-3" viewBox="0 0 16 16">
                    <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z" />
                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                </svg>
            </div>
            <h3 class="m-1">Add a stock to your portfolio!</h3>
            <p>You can easily add stock to your portfolio. Just set the buy price, stock index and the quantity of bought stocks.</p>
            <a class="icon-link" asp-area="" asp-controller="StockPurchases" asp-action="Create">
                Add stocks!
                <svg xmlns="http://www.w3.org/2000/svg" width="1.2rem" height="1.2rem" fill="blue" class="bi bi-chevron-right" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" /></svg>
            </a>
        </div>
        <div class="feature col">
            <div class="feature-icon bg-dark bg-gradient rounded position-relative top-0 start-50 translate-middle-x" style="width:80px">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="white" class="bi bi-collection m-3" viewBox="0 0 16 16">
                    <path d="M2.5 3.5a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-11zm2-2a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1h-7zM0 13a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13V6a1.5 1.5 0 0 0-1.5-1.5h-13A1.5 1.5 0 0 0 0 6v7zm1.5.5A.5.5 0 0 1 1 13V6a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13z" />
                </svg>
            </div>
            <h3 class="m-1">Check out your portfolio!</h3>
            <p>Check how your portfolio of stocks is going. Is it a good time to invest more, or to sell some for profit?</p>
            <a class="icon-link" asp-area="" asp-controller="StockPurchases" asp-action="">
                Check out your portfolio!
                <svg xmlns="http://www.w3.org/2000/svg" width="1.2rem" height="1.2rem" fill="blue" class="bi bi-chevron-right" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" /></svg>
            </a>
        </div>
        <div class="feature col">
            <div class="feature-icon bg-dark bg-gradient rounded position-relative top-0 start-50 translate-middle-x" style="width:80px">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="white" class="bi bi-person-circle m-3" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                </svg>
            </div>
            <h3 class="m-1">Edit your profile!</h3>
            <p>Do not forget to change your password once in a while, security of your account is very important</p>
            <a class="icon-link"  asp-area="Identity" asp-page="/Account/Manage/Index">
                Change things up!
                <svg xmlns="http://www.w3.org/2000/svg" width="1.2rem" height="1.2rem" fill="blue" class="bi bi-chevron-right" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" /></svg>
            </a>
        </div>
    </div>
</div>

StockScreener/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockScreener</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="">
                    <img src="https://emoji.gg/assets/emoji/5827_STONKS.png" alt="" width="30" height="24" class="d-inline-block align-text-top">
                    StockScreener
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="StockPurchases" asp-action="">My Stocks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:greenyellow;" asp-area="" asp-controller="StockPurchases" asp-action="Create">Add purchase</a>
                        </li>
                    </ul>
                    <span class="navbar-text">
                        <partial name="_LoginPartial" />
                    </span>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StockScreener/Views/StockPurchases/Create.cshtml
@model StockScreener.Models.StockPurchase

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StockPurchase</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BoughtAt" class="control-label"></label>
                <input asp-for="BoughtAt" class="form-control"/>
                <span asp-validation-for="BoughtAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockIndex" class="control-label"></label>
                <input asp-for="StockIndex" class="form-control" />
                <span asp-validation-for="StockIndex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SharesQuantity" class="control-label"></label>
                <input asp-for="SharesQuantity" class="form-control"/>
                <span asp-validation-for="SharesQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

StockScreener/Views/StockPurchases/Delete.cshtml
@model StockScreener.Models.StockPurchase

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StockPurchase</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BoughtAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BoughtAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockIndex)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockIndex)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SharesQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SharesQuantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StockScreener/Views/StockPurchases/Details.cshtml
@model StockScreener.Models.StockPurchase

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StockPurchase</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BoughtAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BoughtAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StockIndex)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StockIndex)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SharesQuantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SharesQuantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
</div>
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div id="tradingview_15bca"></div>
    
    <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
    <script type="text/javascript">
        var elements = document.getElementsByClassName("col-sm-10");

        new TradingView.widget(
            {
                "width": 980,
                "height": 610,
                "symbol": elements[1].innerText,
                "interval": "D",
                "timezone": "Etc/UTC",
                "theme": "light",
                "style": "2",
                "locale": "en",
                "toolbar_bg": "#f1f3f6",
                "enable_publishing": false,
                "allow_symbol_change": true,
                "container_id": "tradingview_15bca"
            }
        );
    </script>
</div>
<!-- TradingView Widget END -->
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

StockScreener/Views/StockPurchases/Edit.cshtml
@model StockScreener.Models.StockPurchase

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StockPurchase</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BoughtAt" class="control-label"></label>
                <input asp-for="BoughtAt" class="form-control" />
                <span asp-validation-for="BoughtAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockIndex" class="control-label"></label>
                <input asp-for="StockIndex" class="form-control" />
                <span asp-validation-for="StockIndex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SharesQuantity" class="control-label"></label>
                <input asp-for="SharesQuantity" class="form-control" />
                <span asp-validation-for="SharesQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

StockScreener/Views/StockPurchases/Index.cshtml
@model IEnumerable<StockScreener.Models.StockPurchase>

@{
    ViewData["Title"] = "Index";
}

<h1>Your portfolio</h1>

<p>
    <a asp-action="Create">Add purchase</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BoughtAt) ($)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StockIndex)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SharesQuantity)
            </th>
            <th>
                Win/Loss (in $)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BoughtAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StockIndex)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SharesQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WinLoss)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

StockScreener/Views/StockPurchases/IndexError.cshtml
@{
    ViewData["Title"] = "NotLoggedIn";
}

<h1>Index doesn't exist in Yahoo Finance API</h1>

StockScreener/Views/StockPurchases/InputError.cshtml
@{
    ViewData["Title"] = "InputError";
}

<h1>Please input the values correctly</h1>

StockScreener/Views/StockPurchases/NotLoggedIn.cshtml
@{
    ViewData["Title"] = "NotLoggedIn";
}

<h1>Not Logged In</h1>